export const SET_ARTICLES = 'SET_ARTICLES';
export const SET_URL = 'SET_URL';
export const ADD_SOURCE = 'ADD_SOURCE';

export const FETCHING = 'FETCHING';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';
export const FETCH_TOP_HEADLINES_REQUEST = 'FETCH_TOP_HEADLINES_REQUEST';
export const FETCH_HEADLINES_BY_QUERY_REQUEST =
  'FETCH_HEADLINES_BY_QUERY_REQUEST';
export const FETCH_HEADLINES_BY_SOURCE_REQUEST =
  'FETCH_HEADLINES_BY_SOURCE_REQUEST';
export const FETCH_NEXT_PAGE_REQUEST = 'FETCH_NEXT_PAGE_REQUEST';
export const FETCH_PREVIOUS_PAGE_REQUEST = 'FETCH_PREVIOUS_PAGE_REQUEST';
